### ISSUE TITLE
Template unit vector discrepancies with OpenFold

### ISSUE THREAD

**Issue by amorehead** [lucidrains/alphafold3-pytorch#207]
From Tom in the AlphaFold3 Discord channel:

> The template_unit_vector calculation seems to give entirely different results to the OpenFold implementation (https://github.com/aqlaboratory/openfold/blob/6f63267114435f94ac0604b6d89e82ef45d94484/openfold/utils/feats.py#L143) when applied to the same set of coordinates

Here's our code Tom is most likely referencing (which I wrote without being aware of OpenFold's version of this, which is more likely to be correct): https://github.com/lucidrains/alphafold3-pytorch/blob/496790f539ff7810142ec7a6ec1ebfec01fa0dbc/alphafold3_pytorch/data/template_parsing.py#L382

**Comment by amorehead** [comment]
cc @vandrw

**Comment by vandrw** [comment]
Thanks, @amorehead, for moving the issue here! And thanks for pointing out the code! I'll take a closer look once I've pushed the changes for the other issue. I was initially thinking that the difference occurs probably due to a new algorithm used in AF3, but I'll have to review [this part from OpenFold ](https://github.com/aqlaboratory/openfold/blob/6f63267114435f94ac0604b6d89e82ef45d94484/openfold/utils/rigid_utils.py#L1312-L1382) better to be sure.

Do you happen to have an example input for this? I am not sure exactly how it would be structured. Furthermore, it seems that the code that Tom references focuses on generating this input based on the Nitrogen, Alpha Carbon and Carbon atoms:
```py
n, ca, c = [rc.atom_order[a] for a in ["N", "CA", "C"]]
rigids = Rigid.make_transform_from_reference(
    n_xyz=batch["template_all_atom_positions"][..., n, :],
    ca_xyz=batch["template_all_atom_positions"][..., ca, :],
    c_xyz=batch["template_all_atom_positions"][..., c, :],
    eps=eps,
)
```

Is the approach for AF3 different? Briefly looking at the code, there seems to be no filtering for these atoms when computing the unit vectors.

**Comment by amorehead** [comment]
@vandrw, I recommend debugging the [template feature unit test](https://github.com/lucidrains/alphafold3-pytorch/blob/21da88d35d2a93cae7d28654f69b9c123f035bd7/tests/test_template_loading.py#L13) to see some real PDB complexes running through this function. The key difference between OpenFold's implementation (presumably for AF2) and the AF3 implementation I attempted to write is that the notion of the 3 "frame" atoms (required to construct the frame of amino acid residue, in AF2 parlance) is generalized to all possible molecule types. I've already written all the logic to identify these three "frame" atoms for each "token" (i.e., residue in AF2 parlance), so you can simply focus on the core logic of this displacement unit vector feature itself.

**Comment by amorehead** [comment]
@vandrw, I actually just created a PR to fix the template unit vectors' computation here: https://github.com/lucidrains/alphafold3-pytorch/pull/235
